### ISSUE TITLE
Get working with docker / ruby 2.3 - bundle package

### ISSUE THREAD

**Issue by johndpope** [ging/social_stream-started#1]
I started this branch - but am hitting walls where the dependencies are rotten and want to upgrade to a later ruby v2.5 - and then rails comes unstuck wanting to upgrade. It's a nightmare. Sighh......
If we can get a historical snapshot of this working on docker - it would be very valuable. 
don't need the upstream base / social - those git repos should be archived. 

https://github.com/johndpope/social_stream-started

UPDATE
this helps troubleshoot stalling bundler 

UPDATE
Bundler version 1.11.2 - is 💩

this will install on ruby 2.3
`gem install bundler -v '~> 2.3.26'`

`DEBUG_RESOLVER=1 bundle install --verbose`

UPDATE

now rails breaks
```

  In Gemfile:
    rails (= 3.2.13) was resolved to 3.2.13, which depends on
      bundler (~> 1.0)

  Current Bundler version:
    bundler (2.3.26)

```

UPDATE -3
gem install bundler:1.17.3
bundle _1.17.3_ install --verbose

got bundle to install. happy days

**Comment by johndpope** [comment]
problem now is social social_stream-ostatus

that's related to this proudhon missing gem


```shell
 rails s
/usr/local/bundle/gems/activesupport-3.2.13/lib/active_support/values/time_zone.rb:270: warning: circular argument reference - now
Top level ::CompositeIO is deprecated, require 'multipart/post' and use `Multipart::Post::CompositeReadIO` instead!
Top level ::Parts is deprecated, require 'multipart/post' and use `Multipart::Post::Parts` instead!
/usr/local/bundle/gems/faraday-0.9.2/lib/faraday/upload_io.rb:65: warning: constant ::UploadIO is deprecated
/usr/local/bundle/gems/faraday-0.9.2/lib/faraday/upload_io.rb:66: warning: constant ::Parts is deprecated
/usr/local/bundle/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require': cannot load such file -- social_stream-ostatus (LoadError)
	from /usr/local/bundle/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /usr/local/bundle/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `block in require'
	from /usr/local/bundle/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `require'
	from /myapp/local/social_stream/lib/social_stream.rb:26:in `block in <top (required)>'
	from /myapp/local/social_stream/lib/social_stream.rb:25:in `each'
	from /myapp/local/social_stream/lib/social_stream.rb:25:in `<top (required)>'
	from /usr/local/bundle/gems/bundler-1.17.3/lib/bundler/runtime.rb:81:in `require'
	from /usr/local/bundle/gems/bundler-1.17.3/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
	from /usr/local/bundle/gems/bundler-1.17.3/lib/bundler/runtime.rb:76:in `each'
	from /usr/local/bundle/gems/bundler-1.17.3/lib/bundler/runtime.rb:76:in `block in require'
	from /usr/local/bundle/gems/bundler-1.17.3/lib/bundler/runtime.rb:65:in `each'
	from /usr/local/bundle/gems/bundler-1.17.3/lib/bundler/runtime.rb:65:in `require'
	from /usr/local/bundle/gems/bundler-1.17.3/lib/bundler.rb:114:in `require'
	from /myapp/config/application.rb:7:in `<top (required)>'
	from /usr/local/bundle/gems/railties-3.2.13/lib/rails/commands.rb:53:in `require'
	from /usr/local/bundle/gems/railties-3.2.13/lib/rails/commands.rb:53:in `block in <top (required)>'
	from /usr/local/bundle/gems/railties-3.2.13/lib/rails/commands.rb:50:in `tap'
	from /usr/local/bundle/gems/railties-3.2.13/lib/rails/commands.rb:50:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'
```



https://github.com/ging/vish/issues/132

@atd do you have a copy somewhere?
@edssn has some problem.
